### PR TITLE
Exclude skeleton code

### PR DESCRIPTION
**Pull request by nguyen-mai-huong**
A code mapping is a portion of code that is in common of 2 submissions.
This PR involves modifying how similarity percentage is computed and how to distinguish base code (skeleton code) vs submission code in a code mapping.

Currently, if the submissions contain base code, after obtaining all code mappings, PD engine will find base code within each code mapping. A count is obtained by original number of similar statements in the mapping - number of base codes' statements.

If this count is more than the MML threshold, all code tokens (including base tokens) will be counted in similarity percentage calculation and flag isPlagMapping marked as true. Otherwise, all tokens will be marked as part of base code and not counted in similarity percentage calculation; flag isPlagMapping marked as false.

The updated logic is as follows

After PD engine finds all base codes within the code mapping, tokens from base code will be marked as base tokens and be excluded from similarity percentage calculation. The rest of tokens from the code mapping will be marked as similar tokens. 
We also store information of base codes (start line, end line) within the code mapping.

The marking of flag  isPlagMapping remains the same.

### CODE REVIEW

**Comment by knmnyn** [comment]
Hi @nguyen-mai-huong : I am unsure what you are doing with this closed PR.  Are you refactoring, merging, or some other action?

**Comment by nguyen-mai-huong** [comment]
I merged several commits at my local, and created a new PR. This PR contained non-organized debugging code which could confuse reviewers from checking the code.

**Comment by knmnyn** [comment]
Thanks for your clarification.  Then how do you want the review team to review your code?  I'm not sure I follow your argument.

**Comment by nguyen-mai-huong** [comment]
Could we follow up in this PR? https://github.com/WING-NUS/SSID/pull/131

**Comment by knmnyn** [comment]
Done.  Thanks!

**Pull request closed without merging**
