### PR TITLE
Create a basic docker-compose setup for quick local demo testing

### PR DESCRIPTION
**Pull request by frizensami**
Hello - I wanted to test SSID but I didn't want to install everything locally, so I created a basic `docker` + `docker-compose` configuration to enable quick local testing. This isn't meant for production use, just to get off the ground quicker. 

The instructions to use it as in USING_DOCKER.md, but reproduced here: 

- Copy `config/database.docker.yml` to `config/database.yml`
- Run `docker-compose build`
- Run `docker-compose up`
- Go to 127.0.0.1:3000 in the browser to see the login interface
- Login with username `admin` and password `$$SSIDPassword$$`

Hope this is useful!

### CODE REVIEW

**Comment by knmnyn** [comment]
@Riyas97 : can you confim and update the status here against your own Docker file?  Thanks for your help, to both you and @frizensami

**Comment by knmnyn** [comment]
Thanks for this @frizensami .  We have another docker file but I think @Riyas97 didn't yet merge it.  Likely we will combine or select one to merge into the repository.  Don't worry if we reject your PR; since the material changes will be merged in another  PR.

**Comment by frizensami** [comment]
No problem!

**Review by xiaowudeshen — COMMENTED** [review]
I think the general process is correct and I was using in this way when Riyas help me implement everything. 

Maybe we can suggest that, if the user is accessing the SSID for second time or they did not make change to the library files, they only need to do the 'docker-compose up' instead of 'docker-compose build' which will save time

**Comment by Riyas97** [comment]
I am closing this PR as an similar PR was just created https://github.com/WING-NUS/SSID/pull/143.

**Pull request closed without merging**
